act:				main.o GradeActivity.o FinalExam.o

					g++ main.o GradeActivity.o FinalExam.o -o act

main.o:				main.cpp

					g++ -c main.cpp

GradeActivity.o:	GradeActivity.cpp

					g++ -c GradeActivity.cpp

FinalExam.o:		FinalExam.cpp

					g++ -c FinalExam.cpp
					
run:

					./act

clean:

					rm *.o act