act:			main.o	FeetInches.o

				g++ main.o FeetInches.o	-o act

main.o:			main.cpp

				g++ -c main.cpp

FeetInches.o:	FeetInches.cpp

				g++ -c FeetInches.cpp

run:

				./act

clean:

				rm *.o act