LinkedList:		*.o

				g++ -o LinkedList *.o

*.o:			*.cpp

				g++ -c *.cpp

run:

				./LinkedList

clean:

				rm *.o *.zip LinkedList

zip:

				zip -r LinkedList.zip linkedList.cpp