dynamicArray:	*.o

				g++ -o dynamicArray *.o

*.o:			*.cpp

				g++ -c *.cpp

run:

				./dynamicArray

clean:

				rm *.o *.zip dynamicArray

zip:

				zip -r dynamicArray.zip dynamicArray.cpp