act:				main.o PassFailActivity.o 

					g++ main.o PassFailActivity.o -o act

main.o:				main.cpp

					g++ -c main.cpp

PassFailActivity.o:	PassFailActivity.cpp

					g++ -c PassFailActivity.cpp

run:

					./act

clean:

					rm *.o act