circularList:	*.o

				g++ -o circularList *.o

*.o:			*.cpp

				g++ -c *.cpp

run:

				./circularList

clean:

				rm *.o *.zip circularList

zip:

				zip -r circularList.zip circularList.cpp