act:				main.o GradeActivity.o

					g++ main.o GradeActivity.o -o act

main.o:				main.cpp

					g++ -c main.cpp

GradeActivity.o:	GradeActivity.cpp

					g++ -c GradeActivity.cpp

run:

					./act

clean:

					rm *.o act