act:		main.o Budget.o Auxil.o

			g++ main.o Budget.o Auxil.o -o act

main.o:		main.cpp 

			g++ -c main.cpp

Budget.o:	Budget.cpp

			g++ -c Budget.cpp	

Auxil.o:	Auxil.cpp

			g++ -c Auxil.cpp

run:

		./act

clean:

		rm *.o act